apiVersion: v1
kind: Service
metadata:
  name: ping-service
spec:
  type: NodePort  
  selector:
    app: ping-server  
  ports:
    - port: 80            
      targetPort: 8080    
      nodePort: 30080     